export const ASSIGNABLE_STAFF_PERMISSIONS = [
  "ONBOARD_BUSINESS",
  "VIEW_BUSINESS",
  "UPDATE_BUSINESS",
  "TRAIN_AI",
  "UPLOAD_KNOWLEDGE",
  "CONFIGURE_AGENT",
  "SUPPORT_BUSINESS",
  "MANAGE_STAFF_USERS",
];

export const RESTRICTED_SYSTEM_PERMISSIONS = [
  "DELETE_BUSINESS",
  "CHANGE_SUBSCRIPTION_PRICING",
  "ACCESS_BILLING_SECRETS",
  "SYSTEM_SETTINGS",
  "MANAGE_STAFF_PERMISSIONS",
];

export const ALL_PERMISSIONS = [
  ...ASSIGNABLE_STAFF_PERMISSIONS,
  ...RESTRICTED_SYSTEM_PERMISSIONS,
];
