export const ASSIGNABLE_STAFF_PERMISSIONS = [
  "DASHBOARD_OVERVIEW",
  "TENANT_MANAGEMENT",
  "TENANT_CREATE",
  "TENANT_UPDATE",
  "TENANT_VIEW",
  "TENANT_DELETE",
  "ALL_USER_VIEW",
  "DEMO_BOOKING_VIEW",
  "DEMO_BOOKING_UPDATE",
  "CHATBOT_AGENT_VIEW",
  "CHATBOT_AGENT_KNOWLEDGE_BASE_UPLOAD",
  "CHATBOT_AGENT_KNOWLEDGE_UPDATE",
  "VOICE_AGENT_VIEW",
  "VOICE_AGENT_CREATE",
  "VOICE_AGENT_UPDATE",
  "VOICE_AGENT_TWILIO_NUMBER_ADD",
];

export const RESTRICTED_SYSTEM_PERMISSIONS = [
  "CHANGE_SUBSCRIPTION_PRICING",
  "ACCESS_BILLING_SECRETS",
  "SYSTEM_SETTINGS",
  "MANAGE_STAFF_PERMISSIONS",
];

export const ALL_PERMISSIONS = [
  ...ASSIGNABLE_STAFF_PERMISSIONS,
  ...RESTRICTED_SYSTEM_PERMISSIONS,
];
