// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnnvbb5ViHETDwkRsMpy-qydala6RxX60',
    appId: '1:423817374578:web:ffba2650f063f9b3448beb',
    messagingSenderId: '423817374578',
    projectId: 'tugatai-ai-platform',
    authDomain: 'tugatai-ai-platform.firebaseapp.com',
    storageBucket: 'tugatai-ai-platform.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlKPZSGFH7vEXr2ri5HE9AgAxJwswkZ9M',
    appId: '1:423817374578:android:abc9d439a6bd746d448beb',
    messagingSenderId: '423817374578',
    projectId: 'tugatai-ai-platform',
    storageBucket: 'tugatai-ai-platform.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC5Q5QxqEpGEOI1mhHCJgXx_0aI7CF4eo',
    appId: '1:423817374578:ios:08992675b5292f9f448beb',
    messagingSenderId: '423817374578',
    projectId: 'tugatai-ai-platform',
    storageBucket: 'tugatai-ai-platform.firebasestorage.app',
    iosBundleId: 'com.example.roberto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC5Q5QxqEpGEOI1mhHCJgXx_0aI7CF4eo',
    appId: '1:423817374578:ios:08992675b5292f9f448beb',
    messagingSenderId: '423817374578',
    projectId: 'tugatai-ai-platform',
    storageBucket: 'tugatai-ai-platform.firebasestorage.app',
    iosBundleId: 'com.example.roberto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnnvbb5ViHETDwkRsMpy-qydala6RxX60',
    appId: '1:423817374578:web:272330def4d3a978448beb',
    messagingSenderId: '423817374578',
    projectId: 'tugatai-ai-platform',
    authDomain: 'tugatai-ai-platform.firebaseapp.com',
    storageBucket: 'tugatai-ai-platform.firebasestorage.app',
  );
}
